### ISSUE TITLE
Implement Audit Log

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-backend#52] opened 2015-08-21 18:22 UTC
We need to have audit log support whenever resources are created, modified, or deleted.

http://stackoverflow.com/questions/4754485/dry-way-to-add-created-modified-by-and-time

TODO: which resources?

**Comment by mannyrivera2010** [comment] 2016-07-19 21:06
This ticket seems like a duplicate of #61

**Closed by mannyrivera2010** 2016-07-19 21:06 UTC
